### ISSUE TITLE
Khaos create Unhandled error ENOENT

### ISSUE THREAD

**Issue by akaleeroy** [segmentio/khaos#112]
```
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\pc\AppData\Roaming\npm\node_modules\khaos\bin\khaos-list ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:871:11)
    at internal/main/run_main_module.js:21:11
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:253:12)
    at onErrorNT (internal/child_process.js:431:16)
    [... lines matching original stack trace ...]
    at internal/main/run_main_module.js:21:11
```
Platform: Windows
Node.js v11.13.0

I see the project is abandoned, an alternative scaffolding tool that's as direct, general-purpose and Node-based would be [**scas**](https://www.npmjs.com/package/scas)

**Comment by DanielaCiocoiu** [comment]
Did you find a solution? I have the same issue.

**Comment by akaleeroy** [comment]
@shanti0x Hey fellow Bucharesterner! I didn't find a solution, I went with [**scas**](https://www.npmjs.com/package/scas) in the meantime. I'm looking for a good general solution so I can do more tasks with templates, thinking about going up the stream either to static site generators (maybe Metalsmith) or text editor extensions (Sublime / VS Code)

**Comment by DanielaCiocoiu** [comment]
Thank you for your response, I am a noob and after three days of testing all kind of nerves, in my case solution was to reinstall git.
