### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ehrenglaube** [segmentio/khaos#69]
So, fresh install of Khaos, get this error:

C:\Dev\Projects\Misc>khaos create segmentio/khaos-node my-new-project

events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: spawn C:\Users\Jo\AppData\Roaming\npm\node_modules\khaos\bin\khaos-create
 ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1022:32)
    at child_process.js:1114:20
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:487:11)
    at startup (node.js:112:16)
    at node.js:865:3

**Comment by ouchxp** [comment]
same error happened on my computer

**Comment by lambtron** [comment]
What version of node were you running? Try upgrading to 4.x and seeing if that works.
