### ISSUE TITLE
Error: spawn C:\...\bin\khaos-create ENOENT on Windows

### ISSUE THREAD

**Issue by ArtskydJ** [segmentio/khaos#89]
On Windows:

```
C:\Users\Michael\Github\ktest>khaos create segmentio.khaos-node my-new-project


events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\Michael\AppData\Roaming\nvm\v4.2.1\node_modules\khaos\bin\khaos-create ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:134:18)
    at node.js:961:3
```

The problem is that windows does not recognize [shebangs](https://en.wikipedia.org/wiki/Shebang_%28Unix%29), so [this spawn](https://github.com/segmentio/khaos/blob/master/bin/khaos#L75-L76) does not work.

**Comment by apieceofbart** [comment]
any news on fixing that?

**Comment by ArtskydJ** [comment]
I made a [PR with a fix](https://github.com/segmentio/khaos/pull/90), but this project doesn't seem to be (actively) maintained, so I haven't heard anything from any maintainers...

**Comment by apieceofbart** [comment]
yeah, I saw it - great job! I was hoping my comment would get some attention from the owner..
