### ISSUE TITLE
khaos create error

### ISSUE THREAD

**Issue by chemdemo** [segmentio/khaos#93]
``` bash
E:\code>khaos create node app


events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn D:\Program Files (x86)\nodejs\node_modules\khaos\bin\khaos-create ENOENT
    at exports._errnoException (util.js:860:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
    at Function.Module.runMain (module.js:459:11)
    at startup (node.js:136:18)
    at node.js:972:3
```

Version: 0.9.3
OS: windows 10
Nodejs: v5.0.0

**Comment by loulafripouille** [comment]
I have the same issue:
Version: 0.9.3
OS: Windows 7
Node.js: v5.5.0

**Comment by queckezz** [comment]
Thanks to @ArtskydJ you can temporarily do:

``` bash
 npm install -g ArtskydJ/khaos#patch-1
```
